### PR TITLE
Kim firebase

### PR DESCRIPTION
**Pull request by Bjornsen016**
I have implemented Firebase in the system. 
This way we can store the users in a DB and help them be logged in.
There are a lot of changes in this PR, so please look closely :)

### CODE REVIEW

**Review by Martason — COMMENTED** [review]
Impressive work! Difficult for me to study all the code in detail partly because I honestly don't understand everything, but also because I don't have as much time as I would like. I have two bugs pop up in the app for me.
1. I can no longer log in and instead get {"error":"Cannot read properties of undefined (reading 'uid')"}

Could firebase be the culprit?

2. The hamburger icon is no longer displayed correctly.

**Comment by Bjornsen016** [comment]
> 

Most probably something to do with Firebase or firebase related things.

**Comment by Bjornsen016** [comment]
I looked into the problem. it was on the serverside from Replit. Not in this code. It has been fixed now

**Review by Martason — APPROVED** [review]
Kim the star. Awesome job!

**Pull request merged**
